
package com.raidencentral.app.wsdlartifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "contract-status-update-portService", targetNamespace = "http://www.ouhaogroup.com/contract-status", wsdlLocation = "http://localhost:8080/d171212_producing_web_service_webapp_without_spring_boot_multiple_operations_multiple_artifacts/ws/contract-status-update.wsdl")
public class ContractStatusUpdatePortService
    extends Service
{

    private final static URL CONTRACTSTATUSUPDATEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTRACTSTATUSUPDATEPORTSERVICE_EXCEPTION;
    private final static QName CONTRACTSTATUSUPDATEPORTSERVICE_QNAME = new QName("http://www.ouhaogroup.com/contract-status", "contract-status-update-portService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/d171212_producing_web_service_webapp_without_spring_boot_multiple_operations_multiple_artifacts/ws/contract-status-update.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTRACTSTATUSUPDATEPORTSERVICE_WSDL_LOCATION = url;
        CONTRACTSTATUSUPDATEPORTSERVICE_EXCEPTION = e;
    }

    public ContractStatusUpdatePortService() {
        super(__getWsdlLocation(), CONTRACTSTATUSUPDATEPORTSERVICE_QNAME);
    }

    public ContractStatusUpdatePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTRACTSTATUSUPDATEPORTSERVICE_QNAME, features);
    }

    public ContractStatusUpdatePortService(URL wsdlLocation) {
        super(wsdlLocation, CONTRACTSTATUSUPDATEPORTSERVICE_QNAME);
    }

    public ContractStatusUpdatePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTRACTSTATUSUPDATEPORTSERVICE_QNAME, features);
    }

    public ContractStatusUpdatePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContractStatusUpdatePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContractStatusUpdatePort
     */
    @WebEndpoint(name = "contract-status-update-portSoap11")
    public ContractStatusUpdatePort getContractStatusUpdatePortSoap11() {
        return super.getPort(new QName("http://www.ouhaogroup.com/contract-status", "contract-status-update-portSoap11"), ContractStatusUpdatePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContractStatusUpdatePort
     */
    @WebEndpoint(name = "contract-status-update-portSoap11")
    public ContractStatusUpdatePort getContractStatusUpdatePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ouhaogroup.com/contract-status", "contract-status-update-portSoap11"), ContractStatusUpdatePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTRACTSTATUSUPDATEPORTSERVICE_EXCEPTION!= null) {
            throw CONTRACTSTATUSUPDATEPORTSERVICE_EXCEPTION;
        }
        return CONTRACTSTATUSUPDATEPORTSERVICE_WSDL_LOCATION;
    }

}
