
package com.raidencentral.app.wsdlartifact;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "contract-status-update-port", targetNamespace = "http://www.ouhaogroup.com/contract-status")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContractStatusUpdatePort {


    /**
     * 
     * @param contractStatusUpdateRequest
     */
    @WebMethod
    @Oneway
    public void contractStatusUpdate(
        @WebParam(name = "contractStatusUpdateRequest", targetNamespace = "http://www.ouhaogroup.com/contract-status", partName = "contractStatusUpdateRequest")
        ContractStatusUpdateRequest contractStatusUpdateRequest);

}
